# -*- coding: utf-8 -*-
"""Hypothesis Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sV1HtGvMvJ0z4Qkr5mBkD9HMZzDLboX4

##Kasus #1: Apakah pizza dari restoran A memiliki ukuran pizza yang terdistribusi normal?
"""

import pandas as pd
diameter = pd.read_csv('diameter.csv')
diameter.head()

H0 = "Pizza berdistribusi normal"
H1 = "Pizza tidak berdistribusi normal"
a = 0.05

"""Uji Shapiro"""

from scipy.stats import shapiro
shapiro(diameter)

"""Mencari P-Value"""

p_value = round(shapiro(diameter)[1],2)
p_value

if p_value > a :
    print(H0)
else :
    print(H1)

"""##Kasus 2#: Apakah restoran A dan B menghasilkan diameter pizza yang seragam?"""

pizzas = pd.read_csv('pizzas.csv')
pizzas.head()

"""Uji Normalitas"""

unit_1 = pizzas['Making Unit 1']
unit_2 = pizzas['Making Unit 2']

shapiro(unit_1)

shapiro(unit_2)

p_value_u1 = round(shapiro(unit_1)[1],2)
p_value_u2 = round(shapiro(unit_2)[1],2)

if p_value_u1 > a :
    print(H0)
else :
    print(H1)

if p_value_u2 > a :
    print(H0)
else :
    print(H1)

"""Uji Variansi"""

from scipy.stats import levene

H0 = "Kedua restoran memiliki variansi yang sama"
H1 = "Kedua restoran memiliki perbedaan variansi"

levene (unit_1, unit_2)

variance = round(levene(unit_1, unit_2)[1],2)

if variance > a :
    print(H0)
else :
    print(H1)

"""###2 Sample T-Test untuk Persamaan Varians"""

from scipy.stats import ttest_ind

H0 = "Keduanya tidak memiliki perbedaan yang signifikan"
H1 = "Keduanya memiliki perbedaan yang signifikan"

result = round(ttest_ind(unit_1, unit_2)[1],2)

if result > a :
    print(H0)
else :
    print(H1)